// <auto-generated />
namespace JWT_SampleApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class product_cart_tables_added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product_cart_tables_added));
        
        string IMigrationMetadata.Id
        {
            get { return "202005280537310_product_cart_tables_added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
