// <auto-generated />
namespace JWT_SampleApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class create_app_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_app_user));
        
        string IMigrationMetadata.Id
        {
            get { return "202005210934204_create_app_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
